"""Compact financial vocabulary and explanations used in both interfaces."""
TABS = ("Overview", "Wealth", "Annual Returns", "Rolling Returns", "Outperformance", "Currency",
        "Risk & Drawdowns", "Robustness", "Methodology", "Export")
EXPLANATIONS = {
    "Overview": "Compare reinvested-dividend equity returns on identical dates. Headline cards show native and INR results; the Investor Lens measures both investments in your chosen home currency.",
    "Wealth": "Each line starts from the same amount on the same date. Currency-adjusted lines show final wealth translated back into your home currency. A log scale gives equal space to equal proportional changes.",
    "Annual Returns": "A calendar-year return measures growth from the previous year-end to the next. The first partial starting year is omitted. A partial terminal year is labelled YTD and appears only when enabled. Blue indicates negative returns; amber indicates positive returns, with numeric labels.",
    "Rolling Returns": "A rolling window repeats the same holding period across every eligible monthly starting date. This reduces dependence on one chosen endpoint. Windows overlap and are not independent investments.",
    "Outperformance": "A historical win fraction counts windows where the S&P CAGR exceeded NIFTY in the selected home currency. It is not a probability of future success. Matrices show how the result changes with the start date and holding period.",
    "Currency": "A foreign investment combines local equity growth and exchange-rate movement. Log contributions add exactly; a difference between two CAGRs is only an arithmetic gap. Positive FX contribution is a tailwind, negative is a drag.",
    "Risk & Drawdowns": "Drawdown measures the fall from an earlier peak. Volatility measures monthly variability, annualized; correlation measures co-movement. Currency translation can change all three for a foreign investor.",
    "Robustness": "Overlapping long-term windows share most of their observations. Disjoint windows reduce overlap; a paired moving-block bootstrap resamples contiguous blocks while preserving within-block market and FX dependence. Stationarity and limited history still constrain inference.",
    "Methodology": "Official total-return identities and FX units are verified before use. Market calendars are aligned backward within seven days, never with future data. Cutoffs are asynchronous valuations, not simultaneous tradable prices.",
    "Export": "Offline HTML contains interactive figures, tables, interpretation and methodology for this selected state. Excel contains complete analytical tables; CSV bundles and individual figure HTML files provide reusable research data.",
}
GLOSSARY = {
    "CAGR": "Compound annual growth rate: the constant yearly rate linking starting and ending wealth; not an average of yearly returns.",
    "TRI": "Total Return Index, including reinvested dividends.",
    "Total Return": "Price change plus reinvested dividends; TR is its abbreviation.",
    "Price Return": "Price change alone, excluding dividends; unsuitable as a silent replacement for a total-return benchmark.",
    "Native Currency": "The currency in which the index is quoted: INR for NIFTY and USD for the S&P.",
    "Currency-adjusted Return": "The return after converting an investment's value into the investor's home currency.",
    "Rolling Return": "Return over a fixed holding period repeated across successive dates.",
    "Rolling Window": "The start/end interval for one rolling return.",
    "Excess CAGR": "S&P CAGR minus NIFTY CAGR in the same home currency, expressed in percentage points.",
    "Drawdown": "Percentage fall from the highest wealth value observed so far.",
    "Maximum Drawdown": "Deepest historical peak-to-trough loss within this sample.",
    "Volatility": "Standard deviation of monthly returns, annualized using the square root of 12.",
    "Correlation": "Co-movement from −1 to +1; historical correlation is not a promise of diversification.",
    "Sortino Ratio": "Mean monthly excess over the chosen target, annualized and divided by downside deviation. The annual target is zero, not an estimated risk-free rate.",
    "Calmar Ratio": "CAGR divided by the absolute maximum drawdown.",
    "Ulcer Index": "Root mean square of percentage drawdowns, reflecting depth and time below peaks.",
    "Block Bootstrap": "Resampling contiguous blocks of paired market and FX returns; intervals depend on stationarity.",
    "Endpoint Bias": "A conclusion driven by a chosen start or end date rather than broader holding-period evidence.",
    "Overlapping Windows": "Holding intervals sharing observations; their count overstates independent evidence.",
    "USD/INR": "INR per USD. A rise means INR depreciation against USD.",
    "EUR/INR": "INR per EUR, derived as USD/INR × EUR/USD. A rise means INR depreciation against EUR.",
    "EUR/USD": "USD per EUR; FRED DEXUSEU units are verified before conversion.",
    "Currency Drag": "Negative FX contribution to home-currency growth. Exact log contribution differs from an arithmetic CAGR gap.",
    "Currency Tailwind": "Positive FX contribution to home-currency growth.",
}
CONTEXT_TERMS = {
    "Overview": ["CAGR", "TRI", "Total Return", "Native Currency", "Currency-adjusted Return"],
    "Wealth": ["Native Currency", "Currency-adjusted Return", "CAGR"],
    "Annual Returns": ["Total Return", "Price Return"],
    "Rolling Returns": ["Rolling Return", "Rolling Window", "Excess CAGR", "Overlapping Windows"],
    "Outperformance": ["Excess CAGR", "Endpoint Bias", "Overlapping Windows"],
    "Currency": ["USD/INR", "EUR/INR", "EUR/USD", "Currency Drag", "Currency Tailwind"],
    "Risk & Drawdowns": ["Drawdown", "Maximum Drawdown", "Volatility", "Correlation", "Sortino Ratio", "Calmar Ratio", "Ulcer Index"],
    "Robustness": ["Block Bootstrap", "Overlapping Windows", "Endpoint Bias"],
}
