[theme]
base = "dark"
primaryColor = "#3AA7FF"
backgroundColor = "#060913"
secondaryBackgroundColor = "#0B1223"
textColor = "#F7FBFF"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
